- name: variables from files
  hosts: web
  become: yes
  vars_files:
   - vars.yml
  tasks:
  - name: print the msg from variables
    ansible.builtin.debug:
     msg: "hi {{COURSE}} with {{DURATION}} trainer {{TRAINER}}"
