- name: create ec2 instances
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-0f50b6b1766134a92"
    security_group_id: "sg-0c2419ca62965f945"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: aryan927.shop
  tasks:
  - name: ansible to install boto3 botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      security_group: "{{ security_group_id }}"
      instance_type: "t3.micro"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
    
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"
  - name: create r53  privaterecords
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{item.item}}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      overwrite: true
      wait: true

    loop: "{{ ec2_instances.results }}"

  - name: create r53  public records for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
      wait: true

    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"
      
      