- name: create ec2 instances
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0f50b6b1766134a92
    security_group_id: sg-0c2419ca62965f945
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
  tasks:
    name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: {{ subnet_id }}
      instance_type: t3.micro
      image_id: {{ ami_id }}
    loop: "{{ instances }}"
    register: ec2-instances